Repository seL4/camkes-vm, pull requests merged in 2023-04, with the labels that each got.

#82 github: PR hardware tests for camkes-vm-examples
  .github/workflows/test.yml
Labels: hw-test, CI

#84 github: provide PR sha for hardware test
  .github/workflows/test.yml
Labels: CI

#87 Fix crashes introduced in seL4/camkes-vm#73
  components/VM_Arm/src/main.c
Labels: bug, hw-test
